;****************************************************************
; PlayerController                                              ;
; Responsible for player's movement and graphics                ;
;****************************************************************

;****************************************************************
; Name:                                                         ;
;   RenderExplosion                                             ;
;                                                               ;
; Description:                                                  ;
;   Renders an explosion                                        ;
;                                                               ;
; Input variables:                                              ;
;   todo                                                        ;
;                                                               ;
; Used variables:                                               ;
;   todo                                                        ;
;****************************************************************

RenderExplosion:
  RTS
  
;****************************************************************
; Lookup tables generated by the tool below                     ;
; 117 bytes, could be less since there is a lot of duplication  ;
;****************************************************************
  
xOff1st:
  .byte $05, $00, $00, $00
xOffRest:
  .byte $00, $08, $00, $08
yOff1st:
  .byte $04, CLEAR_SPRITE, CLEAR_SPRITE, CLEAR_SPRITE
yOffRest:
  .byte $00, $00, $08, $08
atts:
  .byte $00, $00, $00, $40
tiles:
  .byte $22, $23, $24, $24
  .byte $1E, $1F, $20, $21
  .byte $1A, $1B, $1C, $1D
  .byte $19, CLEAR_SPRITE, CLEAR_SPRITE, CLEAR_SPRITE
